### PR TITLE
Only specialize distributeGridAndData for CpGrid if MPI is found.

### LINKED ISSUE #526: compiling error of the master branch
with Dune 2.3 and no mpi. 

```
 In file included from /home/kaib/OPM-master-test/build/opm-autodiff/examples/flow.cpp:82:0:
/home/kaib/OPM-master-test/build/opm-autodiff/opm/autodiff/RedistributeDataHandles.hpp: In function ‘void Opm::distributeGridAndData(Dune::CpGrid&, Opm::DeckConstPtr, Opm::EclipseStateConstPtr, Opm::BlackoilStat
e&, Opm::BlackoilPropsAdFromDeck&, Opm::DerivedGeology&, std::shared_ptr<Opm::EclMaterialLawManager<Opm::ThreePhaseMaterialTraits<double, 0, 1, 2> > >&, boost::any&, bool)’:
/home/kaib/OPM-master-test/build/opm-autodiff/opm/autodiff/RedistributeDataHandles.hpp:358:13: error: ‘ParallelIndexSet’ in ‘class Dune::CpGrid’ does not name a type
     typedef Dune::CpGrid::ParallelIndexSet IndexSet;
             ^
/home/kaib/OPM-master-test/build/opm-autodiff/opm/autodiff/RedistributeDataHandles.hpp:359:11: error: ‘IndexSet’ does not name a type
     const IndexSet& local_indices  = grid.getCellIndexSet();
           ^
/home/kaib/OPM-master-test/build/opm-autodiff/opm/autodiff/RedistributeDataHandles.hpp:360:24: error: ‘local_indices’ was not declared in this scope
     for ( auto index : local_indices )
                        ^
```

### PR DESCRIPTION
**Pull request by blattms**
This is my proposed fix for #526. Note that this is yet untested. Hopefully @GitPaean can test it.

Closes #526

### CODE REVIEW

**Comment by GitPaean** [comment]
It fixes the compilation on my side with dune 2.3 and without MPI. 

Closing #526 now.

**Comment by blattms** [comment]
BTW the problem was introduced in PR #523

**Comment by bska** [comment]
This probably needs to go into the release as well.

**Comment by atgeirr** [comment]
> This probably needs to go into the release as well.

Since the contents of #523 has not been picked for the release, it is not necessary.

**Comment by bska** [comment]
>> This probably needs to go into the release as well.
> 
> Since the contents of #523 has not been picked for the release, it is not necessary.

Okay, that's good.  Thanks a lot for the information.

**Comment by bska** [comment]
@blattms said
> Hopefully @GitPaean can test it.

@GitPaean replied
> It fixes the compilation on my side with dune 2.3 and without MPI.

Then I'll merge this into master to restore the CI build.

**Comment by blattms** [comment]
Thanks a lot!
