### ISSUE TITLE
does not compile with stock dune-istl package

### ISSUE THREAD

**Issue by babrodtk** [OPM/opm-autodiff#347]
After commit adac4a799550816c4b369feb3a51f3d47c2608fc (perhaps before also), opm-autodiff does not compile on ubuntu 14.04, stock, with dune-istl version 2.2.1-2 installed via
apt-get install libdune-istl-dev:

```
[  9%] Building CXX object CMakeFiles/opmautodiff.dir/opm/autodiff/NewtonIterationBlackoilCPR.cpp.o
In file included from /home/vagrant/workspace/opm/opm-autodiff/opm/autodiff/NewtonIterationBlackoilCPR.hpp:26:0,
                 from /home/vagrant/workspace/opm/opm-autodiff/opm/autodiff/NewtonIterationBlackoilCPR.cpp:26:
/home/vagrant/workspace/opm/opm-autodiff/opm/autodiff/CPRPreconditioner.hpp:43:38: fatal error: dune/istl/paamg/fastamg.hh: No such file or directory
 #include <dune/istl/paamg/fastamg.hh>
```

More details on installed libdune-istl-dev:
```
vagrant@vagrant:~/workspace/opm/opm-autodiff$ dpkg -s libdune-istl-dev
Package: libdune-istl-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 1037
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Source: dune-istl
Version: 2.2.1-2
Depends: libdune-common-dev (>= 2.2.1)
Pre-Depends: dpkg (>= 1.15.6)
Description: toolbox for solving PDEs -- iterative solvers (development files)
 DUNE, the Distributed and Unified Numerics Environment is a modular toolbox
 for solving partial differential equations (PDEs) with grid-based methods.
 It supports the easy implementation of methods like Finite Elements (FE),
 Finite Volumes (FV), and also Finite Differences (FD).
 .
 This package contains the development files for the iterative solver template
 library.
Original-Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Homepage: http://www.dune-project.org/
```

**Comment by bska** [comment]
Note: I checked a build targeting Dune 2.2.1 not too long ago (around 27th of March of this year) and at the time the build was fine.  I have just kicked off a GCC 4.4 build based on PR #348 which will visit the following configurations
```
{ Debug, Release } x { Dune 2.2.1, Dune 2.3.1 } x { Sequential, MPI }
```
for all modules. I'll have the result in a few hours.  If everything is fine I'll merge that PR into master.

**Comment by atgeirr** [comment]
> If everything is fine I'll merge that PR into master.

I guess I was a little trigger happy there, I merged it before I saw this. It does not break my (2.3) setup, so I think there was no harm done.

**Comment by bska** [comment]
> I think there was no harm done.

For what it's worth, the build run is currently about three quarters through without ill effects so far.  That does suggest that #348 restores the build when targeting Dune 2.2.1 but it's not entirely conclusive yet.

**Comment by atgeirr** [comment]
Closing as fixed.
